---
name: Lint

on: # yamllint disable-line rule:truthy
    push: null
    pull_request: null

permissions: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: npm ci
            - name: Run ESLint
              run: eslint . --ext .js,.jsx,.ts,.tsx
